databases:
  - name: quiz-db
    plan: free
    databaseName: quiz
    user: quiz

services:
  - type: web
    name: quiz-backend
    runtime: python
    rootDir: app/backend
    plan: free
    buildCommand: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
      export PATH="$HOME/.local/bin:$PATH"
      cd ../..
      uv sync --frozen --package quiz-backend
    startCommand: |
      export PATH="$HOME/.local/bin:$PATH"
      uv run uvicorn main:app --host 0.0.0.0 --port $PORT
    #preDeployCommand: |
    #  export PATH="$HOME/.local/bin:$PATH"
    #  uv run python seed.py
    healthCheckPath: /api/v1/quizzes
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quiz-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: MONOREPO_AUTH_URL
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        generateValue: true
